name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  flutter_gif: ^0.0.4
  audioplayers: ^6.4.0
  webview_flutter: ^4.0.0
  video_player: ^2.9.1
  shared_preferences: ^2.2.3
  flutter_cache_manager: ^3.3.1
  path_provider: ^2.1.3
  cached_network_image: ^3.2.3
  supabase_flutter: ^2.0.0
  visibility_detector: ^0.4.0+2
  flutter_secure_storage: ^8.0.0
  file_picker: ^8.1.2
  intl: ^0.19.0
  fl_chart: ^0.68.0
  image_picker: ^1.1.2
  google_fonts: ^6.1.0
  shimmer: ^3.0.0
  carousel_slider: ^4.2.1
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image 1.png
    - assets/81335cd6-f2fb-4bc3-b92c-44dde6f85e30.png
    - assets/abeba-removebg-preview 1.png
    - assets/abeba-removebg-preview 2.png
    - assets/abeba-removebg-preview.png
    - assets/image 2.png
    - assets/top1.png
    - assets/top2.png
    - assets/blue.png
    - assets/topp.png
    - assets/topp2.png
    - assets/maingif.gif
    - assets/tibebb-removebg-preview 1.png
    - assets/image 7.png
    - assets/girl-removebg-preview.png
    - assets/boy.png
    - assets/avatar12.png
    - assets/avatar1.png
    - assets/avatar2.png
    - assets/avatar3.png
    - assets/avatar4.png
    - assets/avatar5.png
    - assets/avatar6.png
    - assets/avatar7.png
    - assets/avatar8.png
    - assets/avatar9.png
    - assets/avatar10.png
    - assets/avatar11.png
    - assets/Vector.png
    - assets/image.png
    - assets/science1.png
    - assets/image3.png
    - assets/Vector3.png
    - assets/Vector2.png
    - assets/finalgif.gif
    - assets/reversed.gif
    - assets/curve1.png
    - assets/1.png
    - assets/2.png
    - assets/3.png
    - assets/4.png
    - assets/back.png
    - assets/background.png
    - assets/sign.png
    - assets/char1.PNG
    - assets/ሀ.png
    - assets/char2.PNG
    - assets/ሁ.png
    - assets/shake.gif
    - assets/birds.gif
    - assets/bird.gif
    - assets/signn.gif
    - assets/stand.gif
    - assets/ሀ.m4a
    - assets/ሁ.m4a
    - assets/ሂ.m4a
    - assets/ሃ.m4a
    - assets/ሄ.m4a
    - assets/ህ.m4a
    - assets/ሆ.m4a
    - assets/ለ.m4a
    - assets/ሉ.m4a
    - assets/ሊ.m4a
    - assets/ላ.m4a
    - assets/ሌ.m4a
    - assets/ል.m4a
    - assets/ሎ.m4a
    - assets/መ.m4a
    - assets/ሙ.m4a
    - assets/ሚ.m4a
    - assets/ማ.m4a
    - assets/ሜ.m4a
    - assets/ም.m4a
    - assets/ሞ.m4a
    - assets/ሠ.m4a
    - assets/ሡ.m4a
    - assets/ሢ.m4a
    - assets/ሣ.m4a
    - assets/ሤ.m4a
    - assets/ሥ.m4a
    - assets/ሦ.m4a
    - assets/ረ.m4a
    - assets/ሩ.m4a
    - assets/ሪ.m4a
    - assets/ራ.m4a
    - assets/ሬ.m4a
    - assets/ር.m4a
    - assets/ሮ.m4a
    - assets/ሸ.m4a
    - assets/ሹ.m4a
    - assets/ሺ.m4a
    - assets/ሻ.m4a
    - assets/ሼ.m4a
    - assets/ሽ.m4a
    - assets/ሾ.m4a
    - assets/ቀ.m4a
    - assets/ቁ.m4a
    - assets/ቂ.m4a
    - assets/ቃ.m4a
    - assets/ቄ.m4a
    - assets/ቅ.m4a
    - assets/ቆ.m4a
    - assets/በ.m4a
    - assets/ቡ.m4a
    - assets/ቢ.m4a
    - assets/ባ.m4a
    - assets/ቤ.m4a
    - assets/ብ.m4a
    - assets/ቦ.m4a
    - assets/ተ.m4a
    - assets/ቱ.m4a
    - assets/ቲ.m4a
    - assets/ታ.m4a
    - assets/ቴ.m4a
    - assets/ት.m4a
    - assets/ቶ.m4a
    - assets/ቸ.m4a
    - assets/ቹ.m4a
    - assets/ቺ.m4a
    - assets/ቻ.m4a
    - assets/ቼ.m4a
    - assets/ች.m4a
    - assets/ቾ.m4a
    - assets/ነ.m4a
    - assets/ኑ.m4a
    - assets/ኒ.m4a
    - assets/ና.m4a
    - assets/ኔ.m4a
    - assets/ን.m4a
    - assets/ኖ.m4a
    - assets/ኘ.m4a
    - assets/ኙ.m4a
    - assets/ኚ.m4a
    - assets/ኛ.m4a
    - assets/ኜ.m4a
    - assets/ኝ.m4a
    - assets/ኞ.m4a
    - assets/አ.m4a
    - assets/ኡ.m4a
    - assets/ኢ.m4a
    - assets/ኣ.m4a
    - assets/ኤ.m4a
    - assets/እ.m4a
    - assets/ኦ.m4a
    - assets/ከ.m4a
    - assets/ኩ.m4a
    - assets/ኪ.m4a
    - assets/ካ.m4a
    - assets/ኬ.m4a
    - assets/ክ.m4a
    - assets/ኮ.m4a
    - assets/ኸ.m4a
    - assets/ኹ.m4a
    - assets/ኺ.m4a
    - assets/ኻ.m4a
    - assets/ኼ.m4a
    - assets/ኽ.m4a
    - assets/ኾ.m4a
    - assets/ወ.m4a
    - assets/ዉ.m4a
    - assets/ዊ.m4a
    - assets/ዋ.m4a
    - assets/ዌ.m4a
    - assets/ው.m4a
    - assets/ዎ.m4a
    - assets/ዘ.m4a
    - assets/ዙ.m4a
    - assets/ዚ.m4a
    - assets/ዛ.m4a
    - assets/ዜ.m4a
    - assets/ዝ.m4a
    - assets/ዞ.m4a
    - assets/ዠ.m4a
    - assets/ዡ.m4a
    - assets/ዢ.m4a
    - assets/ዣ.m4a
    - assets/ዤ.m4a
    - assets/ዥ.m4a
    - assets/ዦ.m4a
    - assets/የ.m4a
    - assets/ዩ.m4a
    - assets/ዪ.m4a
    - assets/ያ.m4a
    - assets/ዬ.m4a
    - assets/ይ.m4a
    - assets/ዮ.m4a
    - assets/ደ.m4a
    - assets/ዱ.m4a
    - assets/ዲ.m4a
    - assets/ዳ.m4a
    - assets/ዴ.m4a
    - assets/ድ.m4a
    - assets/ዶ.m4a
    - assets/ጀ.m4a
    - assets/ጁ.m4a
    - assets/ጂ.m4a
    - assets/ጃ.m4a
    - assets/ጄ.m4a
    - assets/ጅ.m4a
    - assets/ጆ.m4a
    - assets/ገ.m4a
    - assets/ጉ.m4a
    - assets/ጊ.m4a
    - assets/ጋ.m4a
    - assets/ጌ.m4a
    - assets/ግ.m4a
    - assets/ጎ.m4a
    - assets/ጠ.m4a
    - assets/ጡ.m4a
    - assets/ጢ.m4a
    - assets/ጣ.m4a
    - assets/ጤ.m4a
    - assets/ጥ.m4a
    - assets/ጦ.m4a
    - assets/ጨ.m4a
    - assets/ጩ.m4a
    - assets/ጪ.m4a
    - assets/ጫ.m4a
    - assets/ጬ.m4a
    - assets/ጭ.m4a
    - assets/ጮ.m4a
    - assets/ጰ.m4a
    - assets/ጱ.m4a
    - assets/ጲ.m4a
    - assets/ጳ.m4a
    - assets/ጴ.m4a
    - assets/ጵ.m4a
    - assets/ጶ.m4a
    - assets/ጸ.m4a
    - assets/ጹ.m4a
    - assets/ጺ.m4a
    - assets/ጻ.m4a
    - assets/ጼ.m4a
    - assets/ጽ.m4a
    - assets/ጾ.m4a
    - assets/ፈ.m4a
    - assets/ፉ.m4a
    - assets/ፊ.m4a
    - assets/ፋ.m4a
    - assets/ፌ.m4a
    - assets/ፍ.m4a
    - assets/ፎ.m4a
    - assets/ፐ.m4a
    - assets/ፑ.m4a
    - assets/ፒ.m4a
    - assets/ፓ.m4a
    - assets/ፔ.m4a
    - assets/ፕ.m4a
    - assets/ፖ.m4a
    - assets/spaceBG.jpg
    - assets/earth.png
    - assets/charr0.png
    - assets/charr1.png
    - assets/spacemission.png
    - assets/head.png
    - assets/body.png
    - assets/astronaut0.png
    - assets/rocket.png
    - assets/rocket2.png
    - assets/rocket3.png
    - assets/dashrocket.png
    - assets/dashed3.png
    - assets/dashed2.png
    - assets/fullrocket.png
    - assets/bg.jpg
    - assets/jupiter.png
    - assets/venus.png
    - assets/mercury.png
    - assets/neptune.png
    - assets/ethflag.png
    - assets/earth2.png
    - assets/mars.png
    - assets/saturn.png
    - assets/sun.png
    - assets/on.png
    - assets/off.png
    - assets/button1.png
    - assets/button2.png
    - assets/uranus.png
    - assets/background2.png
    - assets/rocketmain.gif
    - assets/meteor.png
    - assets/bluerocket.png
    - assets/explosion.png
    - assets/explosion.gif
    - assets/no1.png
    - assets/no2.jpg
    - assets/no3.jpg
    - assets/no4.jpg
    - assets/no5.jpg
    - assets/no6.jpg
    - assets/lion.png
    - assets/lion2.png
    - assets/hut.png
    - assets/adeyabeba.png
    - assets/one.png
    - assets/elephant.png
    - assets/elephant2.png
    - assets/two.png
    - assets/cover1.png
    - assets/cover2.jpg
    - assets/cover3.jpg
    - assets/avatari.png
    - assets/avatarii.png
    - assets/avatariii.png
    - assets/avatariv.png
    - assets/avatarv.png
    - assets/avatarvi.png
    - assets/avatarvii.png
    - assets/avatarviii.png
    - assets/avatarviiii.png
    - assets/avatar102.png
    - assets/avatar112.png
    - assets/avatar122.png
    - assets/tick.png
    - assets/signlanguage.jpg
    - assets/ants.png
    - assets/math.gif
    - assets/cooking.jpg
    - assets/adventure.jpg
    - assets/5.png
    - assets/ሀ.jpg
    - assets/ለ.jpg
    - assets/ሐ.jpg
    - assets/መ.jpg
    - assets/ሠ.jpg
    - assets/ረ.jpg
    - assets/ሰ.jpg
    - assets/ሸ.jpg
    - assets/ቀ.jpg
    - assets/በ.jpg
    - assets/ተ.jpg
    - assets/ቸ.jpg
    - assets/ኀ.jpg
    - assets/ነ.jpg
    - assets/ኘ.jpg
    - assets/አ.jpg
    - assets/ከ.jpg
    - assets/ኸ.jpg
    - assets/ወ.jpg
    - assets/ዐ.jpg
    - assets/ዘ.jpg
    - assets/ዠ.jpg
    - assets/የ.jpg
    - assets/ደ.jpg
    - assets/ጀ.jpg
    - assets/ገ.jpg
    - assets/ጠ.jpg
    - assets/ጨ.jpg
    - assets/ጰ.jpg
    - assets/ጸ.jpg
    - assets/ፀ.jpg
    - assets/ፈ.jpg
    - assets/ፐ.jpg
    - assets/correct.gif
    - assets/wrong.gif
    - assets/blank.png
    - assets/cover2.png
  
     